[tool.ruff]
line-length = 100
lint.ignore = ["D203"]
format.quote-style = "single"
format.indent-style = "tab"

[tool.black]
line-length = 100
target-version = ['py312']

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = ["tests"]
pythonpath = ['.']
