"""adjust user id type

Revision ID: 6c9960a3fe17
Revises: 197e73d4fe3d
Create Date: 2025-07-11 19:24:05.602082

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c9960a3fe17"
down_revision: Union[str, Sequence[str], None] = "197e73d4fe3d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "user",
        "id",
        existing_type=sa.INTEGER(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "id",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("user", "updated_at")
    # ### end Alembic commands ###
