name: Lint
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python 3
          uses: actions/setup-python@v5
          with:
            python-version: 3.12.3
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Lint with ruff
          run: |
            ruff check --select=E9,F63,F7,F82,I --fix --exit-zero
            ruff format
        - name: Check formatting with black
          uses: psf/black@stable
          with:
            src: ". tests/"
            options: "--check --verbose"
        - name: Run unit tests
          run: |
            pytest
